---
- set_fact:
    real_ansible_host: "{{ ansible_host }}"

- name: 'Configure WIFI'
  copy: src=./conf/wpa_supplicant.conf dest=/etc/wpa_supplicant/wpa_supplicant.conf mode=0600

- name: 'Update APT package cache'
  action: apt update_cache=yes

- name: 'Upgrade APT to the lastest packages'
  action: apt upgrade=safe

- name: define
  set_fact:
    apt_package: "{{ __apt_install_packages | list }}"

- name: 'Install packages using apt'
  apt: "name={{ item }} state=latest"
  with_items: "{{ apt_package }}"
  ignore_errors: True
  register: result

- name: 'Update apt'
  command: apt update 
  when: result|failed # 結果変数が失敗であれば実行

- name: 'Install setuptools'
  command: apt install python-dev python-setuptools -y
  when: result|failed

- name: 'Install pip'
  easy_install: name=pip
  when: result|failed

- name: 'Install python-apt'
  pip: name=python-apt
  when: result|failed

- name: 'Install git package from apt'
  apt: pkg=git force=yes
  when: result|failed

- name: 'Install packages'
  apt: "name={{ item }} state=latest"
  with_items: "{{ apt_package }}"
  when: result|failed

- name: 'Configure dhcpd'
  copy: src=./conf/dhcpcd.conf dest=/etc/dhcpcd.conf

- name: 'Configure autorun_date'
  copy: src=./init.d/autorun_date dest=/etc/init.d/autorun_date mode=0755

- name: 'Register autorun_date to update-rc.d'
  action: update-rc.d /etc/init.d/autorun_date defaults

- name: 'Configure vncboot'
  copy: src=./init.d/vncboot dest=/etc/init.d/vncboot mode=0755

- name: 'Register vncboot to update-rc.d'
  action: update-rc.d /etc/init.d/vncboot defaults

- name: 'Download rclone'
  get_url:
    url="https://downloads.rclone.org/rclone-v1.37-linux-arm.zip"
    dest="/home/pi/"

- name: 'Install rclone'
  command: unzip /home/pi/rclone-v1.37-linux-arm.zip && 
           install -o root -g root -m 0755 -t /home/pi/rclone-v1.37-linux-arm/rclone /usr/bin/rclone

- name: 'Reboot'
  shell: sleep 2 && reboot
  async: 1
  poll: 0
  ignore_errors: true

- name: "Wait for Raspberry PI to come back"
  local_action: wait_for host={{ real_ansible_host }} port=22 state=started delay=30
  become: false
